filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
output.logstash:
  hosts: [ "logstash:5044" ]
#output.elasticsearch:
#  hosts: [ "elasticsearch:9200" ]
setup.kibana:
  host: "http://kibana:5601"